#!/usr/bin/env python
#
# dgst: compute a cryptographic digest of input files or stdin,
# analogous to the "openssl dgst -md5|-sha1|-sha256|-sha512" command.
# Requires the "hashlib" module, in python >= 2.5
#
# Usage: dgst [md5|sha1|sha256|sha384|sha512] [file1 file2 ...]
#
# Author: Shumon Huque <shuque@upenn.edu>
#

import sys, os, hashlib

HASHFUNC = dict(md5    = hashlib.md5,
                sha1   = hashlib.sha1,
                sha224 = hashlib.sha224,
                sha256 = hashlib.sha256,
                sha384 = hashlib.sha384,
                sha512 = hashlib.sha512)

def usage():
    print >>sys.stderr, \
          "Usage: dgst [md5|sha1|sha256|sha384|sha512] [file1 file2 ...]"
    sys.exit(1)


def compute_hash(func, file):
    h = func()
    for line in file:
        h.update(line)
    return h.hexdigest()


if __name__ == '__main__':

    if len(sys.argv) < 2:
        usage()

    hashtype = sys.argv[1]
    if not HASHFUNC.has_key(hashtype):
        usage()
    func = HASHFUNC[hashtype]

    if sys.argv[2:]:
        for arg in sys.argv[2:]:
            if os.path.isfile(arg) != 1:
                print >>sys.stderr, "ERROR: %s isn't a file" % arg
            else:
                print "%s(%s)= %s" % (hashtype, arg, 
                                      compute_hash(func, open(arg)))
    else:
        print "%s(STDIN)= %s" % (hashtype, compute_hash(func, sys.stdin))

    sys.exit(0)
